#!/bin/bash

JOURNAL_DIR="/run/log/journal"

if [ -d "$JOURNAL_DIR" ]; then
    echo "Deleting all logs in $JOURNAL_DIR..."

    rm -rf $JOURNAL_DIR/*

    echo "Restarting systemd-journald service..."
    systemctl restart systemd-journald

    echo "All logs in $JOURNAL_DIR have been deleted."
else
    echo "$JOURNAL_DIR does not exist."
fi

echo "Current journal usage:"
journalctl --disk-usage
